@startuml
'https://plantuml.com/sequence-diagram

class OtherVariables {
    boolean inMeleeRange
    distanceFromTarget
}



abstract class  Attack {
    #name: String
    #dieType: int
    #damageType: DamageType
    #otherEffects: String
}
abstract class SpellAttack {
    #dieVolume: int
    #spellModifier: int
}
class RangedSpellAttack {
    .. Target Based ..
    {static} #targetAC: int
    --
    +print(): void
    +roll(): void
    +damage()
    +attackMonster(): void
}
class SaveSpellAttack {
    #spellSaveDC: int
    .. Target Based ..
    {static} #targetSaveProficiency: int
    --
    +print(): void
    +roll(): void
    +damage()
    +attackMonster(): void
}
class WeaponAttack {
    #dmgBonus: int
    #attackBonus: int
    #numOfAttacks: int
    .. Target Based ..
    {static} #targetAC: int
    --
    +print(): void
    +roll(): void
    +damage()
    +attackMonster(): void
    +WeaponAttack(Weapon)
}
class GreatWeaponAttack {
    #dieType = 6
    #dieVolume = 2
    .. Target Based ..

    --
    +print(): void
    +roll(): void
    +damage()
    +attackMonster(): void
}

Attack <|-- SpellAttack
Attack <|-- WeaponAttack
WeaponAttack <|-- GreatWeaponAttack
SpellAttack <|-- RangedSpellAttack
SpellAttack <|-- SaveSpellAttack

@enduml